#!/bin/sh
for id in "$@"; do
	if [ "${id}" != "$1" ]; then
		info=$(curl -s "pastebin.com/raw/${id}")
		repl=${info// /→}
		rep=${repl//\\n/ }
		echo $rep > /tmp/autoao
		java $1 $(cat /tmp/autoao) | nc termbin.com 9999
		rm /tmp/autoao
	fi
done
