#!/bin/sh
for id in "$@"; do
	if [ "${id}" != "$1" ] && [ "${id}" != "f" ]; then
		info=""
		if [ "$2" != "f" ]; then
			info=$(curl -s "pastebin.com/raw/${id}")
		else
			info=$(cat "${id}")
		fi
		repl=${info// /→}
		rep=${repl//\\n/ }
		echo $rep > /tmp/autoao
		java $1 $(cat /tmp/autoao) | nc termbin.com 9999
		rm /tmp/autoao
	fi
done
